# [lastfmbio.initVars]
## lastfm api
port = 9091
url = "https://ws.audioscrobbler.com/2.0"
apikey = "4e0f1e09df74b64accc9a69008569e65"

# ## rmq
# rmqhost = "rmq"
# rmqport = 5672
# rexch = "lastfm"
# rkey = "lastfm.bio"
# rmquser = "user"
# rmqpass = "pass"
